### ISSUE TITLE
Waffen

### ISSUE THREAD

**Issue by TheLastLeo** [AGameProject/H35#5]
![unbenannt](https://cloud.githubusercontent.com/assets/9078871/10196313/9ecfb7ee-6792-11e5-8d74-8f164f2cc0e4.PNG)

(c) by max :)

**Comment by moeex** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/9251294/10195372/93bbc064-678d-11e5-90f7-7cc99e220075.PNG)

**Comment by TheLastLeo** [comment]
Nahkampf:
Axt
Axt
Axt
Axt

Feutersteinspeer
Dolch
Waffeldolch
Klappmesser

Keule
Ausfahrschwert

**Comment by Linggify** [comment]
vorschlag: ich find post apo ne AK rein zu machen recht komisch 1., und 2. hat die nicht viel mit nem bogen zutun, vllt eher nen compoundbogen.. würd eher passen denk ich

![](http://www.bogenkram.de/wp-content/uploads/2011/05/vollauszug.jpg)

**Comment by moeex** [comment]
also durch was genau möchtest du es jetzt ersetzen? :o

**Comment by Linggify** [comment]
mit nem verbundbogen wie du ihn im bild siehst...

**Comment by Linggify** [comment]
sind stärker und akkurater als normale bögen.. is also nicht exakt das selbe wie die anderen bögen..

**Comment by zhengel2000** [comment]
Verstärkter Verbundbogen/Fortified Compound

**Comment by zhengel2000** [comment]
ein reskin vom Huntsman

**Comment by moeex** [comment]
@toterhaser
